version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - 3306
    environment:
      MYSQL_ROOT_USER: spring
      MYSQL_ROOT_PASSWORD: spring
    volumes:
      - microservices_ds:/var/lib/mysql

volumes:
  microservices_ds:
